std = "lua51" # LuaJit (used by nvim) is based on Lua 5.1

# disabled since duplication with LSP
[lints]
undefined_variable = "allow"
unused_variable = "allow"
empty_if = "allow"
unscoped_variables = "allow"
multiple_statements = "allow"
